apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: resident-donkey-go 
  janus-idp.io/tekton: resident-donkey-go
  backstage.io/kubernetes-id: resident-donkey-go
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: resident-donkey-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  