apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: resident-donkey-go
  janus-idp.io/tekton: resident-donkey-go
  backstage.io/kubernetes-id: resident-donkey-go
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: resident-donkey-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
