apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: resident-donkey-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: resident-donkey-go 
  name: resident-donkey-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: resident-donkey-go 
